[build]
  command = "npm run build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[redirects]]
from = "/nbacup/*"
to = "https://stunning-brioche-52b12c.netlify.app/"
status = 200
force = true
